In [5]:
import numpy as np

In [34]:
def KmerProbability(profile, kmer):
  probability = 1
  for nucleotide in enumerate(kmer):
    probability = probability * profile[NucleotideIndex(nucleotide[1]), nucleotide[0]]
  return probability

In [35]:
def NucleotideIndex(nucleotide):
  if nucleotide == 'A':
    return 0
  elif nucleotide == 'C':
    return 1
  elif nucleotide == 'G':
    return 2
  else:
    return 3

In [36]:
def FindAllKmers(dna_string, k):
  kmers_list = []
  for kmer_end_index in range(k - 1, len(dna_string)):
    kmers_list.append(dna_string[kmer_end_index + 1 - k:kmer_end_index + 1])
  return kmers_list

In [51]:
def ProfileMostProbableKmer(text, k, profile):
  highest_probability = 0
  profile_most_probable_kmer = str()
  for kmer in FindAllKmers(text, k):
    if highest_probability < KmerProbability(profile, kmer):
      highest_probability = KmerProbability(profile, kmer)
      profile_most_probable_kmer = kmer
  return profile_most_probable_kmer

In [45]:
text = 'ACCTGTTTATTGCCTAAGTTCCGAACAAACCCAATATAGCCCGAGGGCCT'

In [46]:
k = 5

In [47]:
profile_values = [
0.2, 0.2, 0.3, 0.2, 0.3,
0.4, 0.3, 0.1, 0.5, 0.1,
0.3, 0.3, 0.5, 0.2, 0.4,
0.1, 0.2, 0.1, 0.1, 0.2
]

In [48]:
profile = np.full((4,k), np.reshape(profile_values, (4,k)))

In [49]:
profile

array([[0.2, 0.2, 0.3, 0.2, 0.3],
       [0.4, 0.3, 0.1, 0.5, 0.1],
       [0.3, 0.3, 0.5, 0.2, 0.4],
       [0.1, 0.2, 0.1, 0.1, 0.2]])

In [52]:
ProfileMostProbableKmer(text, k, profile)

'CCGAG'

In [53]:
text = 'CGGATGAGCTCCAGAACTGATCCTGTAGCTAAGCCGAGTAGCACGAACAAACCGAGGAGCACTGGGAACTGAGCTTACTGCCGAAGTATCACGCTACAGATGCTCATGTTTCATCGCCACAGCAGACCGCTAGTGACGACTCGAGGCGTCGCTCCCAAGCAGTGTAAAGTGCTGGTCCCACCCATTACCGGATCCCCTGG'

In [54]:
k = 7

In [55]:
profile_values = [
0.179, 0.214, 0.107, 0.25, 0.179, 0.357, 0.321,
0.357, 0.214, 0.357, 0.214, 0.357, 0.143, 0.393,
0.179, 0.321, 0.214, 0.214, 0.179, 0.286, 0.179,
0.286, 0.25, 0.321, 0.321, 0.286, 0.214, 0.107
]

In [56]:
profile = np.full((4,k), np.reshape(profile_values, (4,k)))

In [57]:
profile

array([[0.179, 0.214, 0.107, 0.25 , 0.179, 0.357, 0.321],
       [0.357, 0.214, 0.357, 0.214, 0.357, 0.143, 0.393],
       [0.179, 0.321, 0.214, 0.214, 0.179, 0.286, 0.179],
       [0.286, 0.25 , 0.321, 0.321, 0.286, 0.214, 0.107]])

In [58]:
ProfileMostProbableKmer(text, k, profile)

'CTCCCAA'

In [59]:
text = 'TCCCTACGTCTTAGACGAGTCAAGGCCTTCGTTAGAGAGCAACGGAGTTAAATATTAATATTACAAACCTCGCCCCAGCCTTCGCCAATTACGATAGACGGGCAGTGGTTGGAGGAAAAATATTAGAGACCACACCAAGCGTTGTTAAGTGTCGATAAGAAGTATCGGGATAACTTATTGATTCGTTTTCTAGCTCAACT'

In [60]:
k = 6

In [61]:
profile_values = [
0.303, 0.364, 0.303, 0.242, 0.303, 0.273,
0.182, 0.303, 0.212, 0.212, 0.212, 0.212,
0.303, 0.152, 0.212, 0.485, 0.333, 0.333,
0.212, 0.182, 0.273, 0.061, 0.152, 0.182
]

In [62]:
profile = np.full((4,k), np.reshape(profile_values, (4,k)))

In [63]:
profile

array([[0.303, 0.364, 0.303, 0.242, 0.303, 0.273],
       [0.182, 0.303, 0.212, 0.212, 0.212, 0.212],
       [0.303, 0.152, 0.212, 0.485, 0.333, 0.333],
       [0.212, 0.182, 0.273, 0.061, 0.152, 0.182]])

In [64]:
ProfileMostProbableKmer(text, k, profile)

'GACGGG'